application: phonenumbervalidator
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
